/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "DATABASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NEXTAUTH_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NEXTAUTH_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TaskManager": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}

import "sst"
export {}